/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.project.view;

/**
 *
 * @author Hallan
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalFrame
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        labelCpfLogin = new javax.swing.JLabel();
        textCpfLogin = new javax.swing.JTextField();
        labelSenhaLogin = new javax.swing.JLabel();
        textSenhaLogin = new javax.swing.JPasswordField();
        buttonLogar = new javax.swing.JButton();
        buttonEsqueciSenha = new javax.swing.JButton();
        buttonCadastar = new javax.swing.JButton();
        panelImagenPrincipal = new javax.swing.JPanel();
        imagemPrincipal = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SPEHOP - Sistema de Prontuário Eletrônico dos Hospitais Públicos");
        setBackground(new java.awt.Color(255, 255, 255));

        panelLogin.setBackground(new java.awt.Color(102, 102, 102));

        labelCpfLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelCpfLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelCpfLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelCpfLogin.setText("CPF");

        textCpfLogin.setBackground(new java.awt.Color(255, 255, 255));
        textCpfLogin.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        textCpfLogin.setForeground(new java.awt.Color(0, 0, 0));
        textCpfLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textCpfLogin.setMargin(new java.awt.Insets(-10, 0, 0, 0));
        textCpfLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCpfLoginActionPerformed(evt);
            }
        });

        labelSenhaLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelSenhaLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelSenhaLogin.setText("SENHA");

        textSenhaLogin.setBackground(new java.awt.Color(255, 255, 255));
        textSenhaLogin.setFont(new java.awt.Font("Dialog", 0, 28)); // NOI18N
        textSenhaLogin.setForeground(new java.awt.Color(0, 0, 0));
        textSenhaLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textSenhaLogin.setMargin(new java.awt.Insets(0, 0, -10, 0));

        buttonLogar.setBackground(new java.awt.Color(204, 204, 204));
        buttonLogar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonLogar.setForeground(new java.awt.Color(0, 0, 0));
        buttonLogar.setText("ENTRAR");
        buttonLogar.setFocusPainted(false);
        buttonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogarActionPerformed(evt);
            }
        });

        buttonEsqueciSenha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        buttonEsqueciSenha.setForeground(new java.awt.Color(255, 255, 255));
        buttonEsqueciSenha.setText("esqueci minha senha");
        buttonEsqueciSenha.setBorder(null);
        buttonEsqueciSenha.setContentAreaFilled(false);
        buttonEsqueciSenha.setFocusCycleRoot(true);
        buttonEsqueciSenha.setMargin(new java.awt.Insets(-10, 14, 2, 14));
        buttonEsqueciSenha.setRolloverEnabled(true);
        buttonEsqueciSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEsqueciSenhaActionPerformed(evt);
            }
        });

        buttonCadastar.setBackground(new java.awt.Color(204, 204, 204));
        buttonCadastar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonCadastar.setForeground(new java.awt.Color(0, 0, 0));
        buttonCadastar.setText("CADASTRAR-SE");
        buttonCadastar.setFocusPainted(false);
        buttonCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginLayout.createSequentialGroup()
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonEsqueciSenha))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(labelSenhaLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(110, 110, 110))
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(labelCpfLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(135, 135, 135))
                            .addComponent(textCpfLogin)
                            .addComponent(textSenhaLogin)
                            .addGroup(panelLoginLayout.createSequentialGroup()
                                .addComponent(buttonLogar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCadastar)))))
                .addGap(25, 25, 25))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelCpfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCpfLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelSenhaLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonEsqueciSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLogar)
                    .addComponent(buttonCadastar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelImagenPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        imagemPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        imagemPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/project/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelImagenPrincipalLayout = new javax.swing.GroupLayout(panelImagenPrincipal);
        panelImagenPrincipal.setLayout(panelImagenPrincipalLayout);
        panelImagenPrincipalLayout.setHorizontalGroup(
            panelImagenPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenPrincipalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(imagemPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        panelImagenPrincipalLayout.setVerticalGroup(
            panelImagenPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagenPrincipalLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imagemPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelImagenPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagenPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textCpfLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCpfLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCpfLoginActionPerformed

    private void buttonLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogarActionPerformed

    private void buttonEsqueciSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEsqueciSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEsqueciSenhaActionPerformed

    private void buttonCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCadastarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastar;
    private javax.swing.JButton buttonEsqueciSenha;
    private javax.swing.JButton buttonLogar;
    private javax.swing.JLabel imagemPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCpfLogin;
    private javax.swing.JLabel labelSenhaLogin;
    private javax.swing.JPanel panelImagenPrincipal;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JTextField textCpfLogin;
    private javax.swing.JPasswordField textSenhaLogin;
    // End of variables declaration//GEN-END:variables
}
