/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.project.view;

import javax.swing.JOptionPane;

/**
 *
 * @author Hallan
 */
public class RegisterWindow extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegisterWindow
     */
    public RegisterWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPanel = new javax.swing.JPanel();
        informacaoRegisterPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        susCardLabel = new javax.swing.JLabel();
        susCardTextField = new javax.swing.JTextField();
        cpfLabel = new javax.swing.JLabel();
        cpfTextField = new javax.swing.JFormattedTextField();
        rgLabel = new javax.swing.JLabel();
        rgTextField = new javax.swing.JTextField();
        nascimentoLabel = new javax.swing.JLabel();
        nascimentoTextField = new javax.swing.JFormattedTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneDddLabel = new javax.swing.JLabel();
        phoneDddTextField = new javax.swing.JTextField();
        phoneNumeroLabel = new javax.swing.JLabel();
        phoneNumeroTextField = new javax.swing.JTextField();
        adressLabel = new javax.swing.JLabel();
        adressTextField = new javax.swing.JTextField();
        adressNumberLabel = new javax.swing.JLabel();
        adressNumberTextField = new javax.swing.JTextField();
        adressNeighborhoodLabel = new javax.swing.JLabel();
        adressNeighborhoodTextField = new javax.swing.JTextField();
        adressCityLabel = new javax.swing.JLabel();
        adressCityTextField = new javax.swing.JTextField();
        adressCepLabel = new javax.swing.JLabel();
        adressCepTextField = new javax.swing.JFormattedTextField();
        titleInformations = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        SmallImage = new javax.swing.JLabel();

        setBorder(null);

        registerPanel.setBackground(new java.awt.Color(51, 51, 51));

        informacaoRegisterPanel.setBackground(new java.awt.Color(204, 204, 204));

        nameLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 0, 0));
        nameLabel.setText("NOME*");

        nameTextField.setBackground(new java.awt.Color(255, 255, 255));
        nameTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nameTextField.setForeground(new java.awt.Color(51, 51, 51));
        nameTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        susCardLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        susCardLabel.setForeground(new java.awt.Color(0, 0, 0));
        susCardLabel.setText("CARTÃO SUS*");

        susCardTextField.setBackground(new java.awt.Color(255, 255, 255));
        susCardTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        susCardTextField.setForeground(new java.awt.Color(0, 0, 0));

        cpfLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cpfLabel.setForeground(new java.awt.Color(0, 0, 0));
        cpfLabel.setText("CPF*");

        cpfTextField.setBackground(new java.awt.Color(255, 255, 255));
        cpfTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        cpfTextField.setForeground(new java.awt.Color(0, 0, 0));
        try {
            cpfTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfTextField.setFont(new java.awt.Font("Dialog", 0, 19)); // NOI18N
        cpfTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfTextFieldActionPerformed(evt);
            }
        });

        rgLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        rgLabel.setForeground(new java.awt.Color(0, 0, 0));
        rgLabel.setText("RG*");

        rgTextField.setBackground(new java.awt.Color(255, 255, 255));
        rgTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rgTextField.setForeground(new java.awt.Color(0, 0, 0));

        nascimentoLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nascimentoLabel.setForeground(new java.awt.Color(0, 0, 0));
        nascimentoLabel.setText("DATA DE NASCIMENTO*");

        nascimentoTextField.setBackground(new java.awt.Color(255, 255, 255));
        nascimentoTextField.setForeground(new java.awt.Color(0, 0, 0));
        try {
            nascimentoTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nascimentoTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nascimentoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nascimentoTextFieldActionPerformed(evt);
            }
        });

        phoneLabel.setBackground(new java.awt.Color(255, 255, 255));
        phoneLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phoneLabel.setForeground(new java.awt.Color(0, 0, 0));
        phoneLabel.setText("TELEFONE:");

        phoneDddLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phoneDddLabel.setForeground(new java.awt.Color(0, 0, 0));
        phoneDddLabel.setText("DDD*");

        phoneDddTextField.setBackground(new java.awt.Color(255, 255, 255));
        phoneDddTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        phoneDddTextField.setForeground(new java.awt.Color(0, 0, 0));

        phoneNumeroLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        phoneNumeroLabel.setForeground(new java.awt.Color(0, 0, 0));
        phoneNumeroLabel.setText("NÚMERO*");

        phoneNumeroTextField.setBackground(new java.awt.Color(255, 255, 255));
        phoneNumeroTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        phoneNumeroTextField.setForeground(new java.awt.Color(0, 0, 0));

        adressLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adressLabel.setForeground(new java.awt.Color(0, 0, 0));
        adressLabel.setText("ENDEREÇO*");

        adressTextField.setBackground(new java.awt.Color(255, 255, 255));
        adressTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adressTextField.setForeground(new java.awt.Color(0, 0, 0));
        adressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressTextFieldActionPerformed(evt);
            }
        });

        adressNumberLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adressNumberLabel.setForeground(new java.awt.Color(0, 0, 0));
        adressNumberLabel.setText("Nº*");

        adressNumberTextField.setBackground(new java.awt.Color(255, 255, 255));
        adressNumberTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adressNumberTextField.setForeground(new java.awt.Color(0, 0, 0));

        adressNeighborhoodLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adressNeighborhoodLabel.setForeground(new java.awt.Color(0, 0, 0));
        adressNeighborhoodLabel.setText("BAIRRO*");

        adressNeighborhoodTextField.setBackground(new java.awt.Color(255, 255, 255));
        adressNeighborhoodTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adressNeighborhoodTextField.setForeground(new java.awt.Color(0, 0, 0));

        adressCityLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adressCityLabel.setForeground(new java.awt.Color(0, 0, 0));
        adressCityLabel.setText("CIDADE*");

        adressCityTextField.setBackground(new java.awt.Color(255, 255, 255));
        adressCityTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        adressCityTextField.setForeground(new java.awt.Color(0, 0, 0));

        adressCepLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        adressCepLabel.setForeground(new java.awt.Color(0, 0, 0));
        adressCepLabel.setText("CEP*");

        adressCepTextField.setBackground(new java.awt.Color(255, 255, 255));
        adressCepTextField.setForeground(new java.awt.Color(0, 0, 0));
        try {
            adressCepTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        adressCepTextField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        titleInformations.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        titleInformations.setForeground(new java.awt.Color(0, 0, 0));
        titleInformations.setText("INFORME SEUS DADOS");

        javax.swing.GroupLayout informacaoRegisterPanelLayout = new javax.swing.GroupLayout(informacaoRegisterPanel);
        informacaoRegisterPanel.setLayout(informacaoRegisterPanelLayout);
        informacaoRegisterPanelLayout.setHorizontalGroup(
            informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                        .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameTextField))
                            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                .addComponent(susCardLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(susCardTextField)
                                .addGap(41, 41, 41)
                                .addComponent(cpfLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                        .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(43, 43, 43)
                                        .addComponent(phoneDddLabel))
                                    .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                        .addComponent(rgLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rgTextField)))
                                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(nascimentoLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nascimentoTextField))
                                    .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(phoneDddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(phoneNumeroLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phoneNumeroTextField)))))
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacaoRegisterPanelLayout.createSequentialGroup()
                        .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                .addComponent(adressCepLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adressCepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(371, 371, 371))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacaoRegisterPanelLayout.createSequentialGroup()
                                .addComponent(adressNeighborhoodLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adressNeighborhoodTextField)
                                .addGap(49, 49, 49)
                                .addComponent(adressCityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adressCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                                .addComponent(adressLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adressTextField)
                                .addGap(18, 18, 18)
                                .addComponent(adressNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adressNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacaoRegisterPanelLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(titleInformations, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addGap(149, 149, 149))
        );
        informacaoRegisterPanelLayout.setVerticalGroup(
            informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacaoRegisterPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titleInformations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(susCardLabel)
                    .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(susCardTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cpfLabel)
                        .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLabel)
                    .addComponent(rgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nascimentoLabel)
                    .addComponent(nascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(phoneDddLabel)
                    .addComponent(phoneDddTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumeroLabel)
                    .addComponent(phoneNumeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressLabel)
                    .addComponent(adressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressNumberLabel)
                    .addComponent(adressNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressNeighborhoodLabel)
                    .addComponent(adressNeighborhoodTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adressCityLabel)
                    .addComponent(adressCityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(informacaoRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adressCepLabel)
                    .addComponent(adressCepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        registerButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        registerButton.setText("CADASTRAR-SE");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        exitButton.setText("SAIR");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        SmallImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/project/img/logoPequeno.png"))); // NOI18N

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SmallImage))
                    .addGroup(registerPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registerButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacaoRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(informacaoRegisterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SmallImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(registerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_exitButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:

        //colocar métodos save

        JOptionPane.showMessageDialog(this, "salvo com sucesso");

        this.setVisible(false);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void adressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressTextFieldActionPerformed

    private void nascimentoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nascimentoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nascimentoTextFieldActionPerformed

    private void cpfTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SmallImage;
    private javax.swing.JLabel adressCepLabel;
    private javax.swing.JFormattedTextField adressCepTextField;
    private javax.swing.JLabel adressCityLabel;
    private javax.swing.JTextField adressCityTextField;
    private javax.swing.JLabel adressLabel;
    private javax.swing.JLabel adressNeighborhoodLabel;
    private javax.swing.JTextField adressNeighborhoodTextField;
    private javax.swing.JLabel adressNumberLabel;
    private javax.swing.JTextField adressNumberTextField;
    private javax.swing.JTextField adressTextField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JFormattedTextField cpfTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel informacaoRegisterPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel nascimentoLabel;
    private javax.swing.JFormattedTextField nascimentoTextField;
    private javax.swing.JLabel phoneDddLabel;
    private javax.swing.JTextField phoneDddTextField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JLabel phoneNumeroLabel;
    private javax.swing.JTextField phoneNumeroTextField;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JTextField rgTextField;
    private javax.swing.JLabel susCardLabel;
    private javax.swing.JTextField susCardTextField;
    private javax.swing.JLabel titleInformations;
    // End of variables declaration//GEN-END:variables
}
